POS_System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
]

core/urls.py
from django.urls import path
from core import views, setupviews, purchaseviews, stockviews, saleviews, reportviews
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', RedirectView.as_view(url='/home')),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    
    path('accounts/index/', views.userlist, name='userlist'),
    # path('accounts/logout/', views.logout, name='logout'),
    path('accounts/logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('accounts/register/', views.registerpage, name='register'),
    path('accounts/login/', views.loginpage, name='login'),
    path('accounts/edit/<int:userid>', views.edituser, name='edituser'),
    path('accounts/delete/', views.deleteuser, name='deleteuser'),
    
    path('company/index/', setupviews.companylist, name='companylist'),
    path('company/create/', setupviews.createcompany, name='createcompany'),
    path('company/edit/<int:id>', setupviews.editcompany, name='editcompany'),
    path('company/delete/', setupviews.deletecompany, name='deletecompany'),
    
    path('supplier/index/', setupviews.supplierlist, name='supplierlist'),
    path('supplier/create/', setupviews.createsupplier, name='createsupplier'),
    path('supplier/edit/<int:id>', setupviews.editsupplier, name='editsupplier'),
    path('supplier/delete/', setupviews.deletesupplier, name='deletesupplier'),
    
    path('customer/index/', setupviews.customerlist, name='customerlist'),
    path('customer/create/', setupviews.createcustomer, name='createcustomer'),
    path('customer/edit/<int:id>', setupviews.editcustomer, name='editcustomer'),
    path('customer/delete/', setupviews.deletecustomer, name='deletecustomer'),
    
    path('category/index/', setupviews.categorylist, name='categorylist'),
    path('category/create/', setupviews.createcategory, name='createcategory'),
    path('category/edit/<int:id>', setupviews.editcategory, name='editcategory'),
    path('category/delete/', setupviews.deletecategory, name='deletecategory'),
    
    path('product/index/', setupviews.productlist, name='productlist'),
    path('product/create/', setupviews.createproduct, name='createproduct'),
    path('product/edit/<int:id>', setupviews.editproduct, name='editproduct'),
    path('product/delete/', setupviews.deleteproduct, name='deleteproduct'),
    path('product/get/', setupviews.getproduct, name='getproduct'),
    path('product/getinfo/', setupviews.getproductinfo, name='getproductinfo'),
    
    path('purchase/index/', purchaseviews.purchaselist, name='purchaselist'),
    path('purchase/create/', purchaseviews.createpurchase, name='createpurchase'),
    path('purchase/edit/<int:id>', purchaseviews.editpurchase, name='editpurchase'),
    path('purchase/delete/', purchaseviews.deletepurchase, name='deletepurchase'),
    
    path('stock/index/', stockviews.stocklist, name='stocklist'),
    path('stock/edit/<int:id>', stockviews.editstock, name='editstock'),
    
    path('sale/index/', saleviews.salelist, name='salelist'),
    path('sale/create/', saleviews.createsale, name='createsale'),
    path('sale/refund/<int:id>', saleviews.refundsale, name='refundsale'),
    path('sale/delete/', saleviews.deletesale, name='deletesale'),
    
    path('report/purchaseSummary/', reportviews.purchaseSummary, name='purchaseSummary'),
    path('report/productInStock/', reportviews.productInStock, name='productInStock'),
    path('report/salesSummary/', reportviews.salesSummary, name='salesSummary'),
    path('report/salesByCustomer/', reportviews.salesByCustomer, name='salesByCustomer'),
    
    path('due/index/', saleviews.duelist, name='duelist'),
    path('due/collection/<int:id>', saleviews.duecollection, name='duecollection'),
    
    path('profile/', views.profile, name='profile'),
    path('profile/createaddress/', views.createaddressprofile, name='createaddressprofile'),
    path('profile/deleteaddress/<int:id>', views.deleteaddressprofile, name='address_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from email.policy import default
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from phonenumber_field.modelfields import PhoneNumberField


STATUS = (
    ('paid', 'Paid'),
    ('due', 'Due'),
    ('refund', 'Refunded'),
)

GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
)

Unit = (
    ('kg', 'KG'),
    ('litre', 'Litre'),
    ('piece', 'Piece'),
    ('feet', 'Feet'),
)

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    fullName = models.CharField(max_length=400, blank=True)
    birthDate = models.DateField(null=True, blank=True)
    gender = models.CharField(choices=GENDER, max_length=20, blank=True, null=True)
    phone = PhoneNumberField(blank=True)
    entryDate = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.fullName


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    addressName = models.CharField(max_length=400, blank=True)
    streetAddress = models.CharField(max_length=100)
    area = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.streetAddress}, {self.area}, {self.city}, {self.country}"

    class Meta:
        verbose_name_plural = 'Addresses'


class Company(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    contact = PhoneNumberField(blank=True)

    def __str__(self):
        return self.name


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    contact = PhoneNumberField(blank=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    contact = PhoneNumberField(blank=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=100)
    code = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=100)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, blank=True, null=True)
    productCode = models.CharField(max_length=100)
    # price = models.FloatField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    lowStockLimit = models.FloatField()
    unit = models.CharField(choices=Unit, max_length=20)
    # quantity = models.IntegerField(default=0)
    # entrydate = models.DateField(null=True, blank=True)
    # sold = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title} ({self.productCode})'

    # def get_absolute_url(self):
    #     return reverse("core:product", kwargs={
    #         'slug': self.productCode
    #     })


class Purchase(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    company = models.ForeignKey(Company, on_delete=models.PROTECT)
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT)
    invoice = models.CharField(max_length=100)
    totalPrice = models.FloatField()
    note = models.TextField(null=True, blank=True)
    entryDate = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f'{self.user} - {self.entryDate.strftime("%Y-%m-%d %H:%M:%S")}'


class PurchaseDetail(models.Model):
    purchase = models.ForeignKey(Purchase, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    tradePrice = models.FloatField()
    totalPrice = models.FloatField()
    
    def __str__(self):
        return f"{self.product} - {self.quantity}"


class Stock(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    purchase = models.ForeignKey(Purchase, on_delete=models.SET_NULL, blank=True, null=True)
    purchasedetail = models.ForeignKey(PurchaseDetail, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0)
    sold = models.IntegerField(default=0)
    tradePrice = models.FloatField()
    salePrice = models.FloatField()
    mrp = models.FloatField()
    discount = models.IntegerField(default=0)
    entryDate = models.DateTimeField(null=True, blank=True)
    manufacturingDate = models.DateField(null=True, blank=True)
    expirationDate = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.product.title}"

    def get_total_item_price(self):
        return self.quantity * self.tradePrice

    def get_total_discount_item_price(self):
        return self.quantity * self.tradePrice * (1 - (self.discount/100.00))

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        return self.get_total_discount_item_price()


class Sale(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    saleStripeId = models.CharField(max_length=20, blank=True, null=True)
    date = models.DateTimeField()
    totalPrice = models.FloatField()
    discountAmount = models.FloatField(default=0)
    paidAmount = models.FloatField(default=0)
    changeAmount = models.FloatField(default=0)
    status = models.CharField(choices=STATUS, max_length=20)
    note = models.TextField()

    def __str__(self):
        return f'{self.user} - {self.date.strftime("%Y-%m-%d %H:%M:%S")}'
    
    def get_dueAmount(self):
        return self.totalPrice - self.discountAmount - self.paidAmount + self.changeAmount


class SaleDetail(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    unitPrice = models.FloatField()
    discount = models.FloatField(default=0)
    totalPrice = models.FloatField()

    def __str__(self):
        return f"{self.quantity} of {self.product.title}"

    def get_total_item_price(self):
        return self.quantity * self.unitPrice

    def get_amount_saved(self):
        return self.get_total_item_price()

    def get_final_price(self):
        return self.get_total_item_price()
    
    
class Due(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    dueAmount = models.FloatField()
    date = models.DateTimeField()
    
    def __str__(self):
        return f"{self.sale} on {self.date}"


class DueCollection(models.Model):
    due = models.ForeignKey(Due, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    date = models.DateTimeField()
    note = models.TextField()
    
    def __str__(self):
        return f"Collected by {self.user} on {self.date}"
    
    
class Refund(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    saleDetail = models.ForeignKey(SaleDetail, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    unitPrice = models.FloatField()
    totalRefund = models.FloatField()
    dueRefund = models.FloatField()
    date = models.DateTimeField()
    note = models.TextField()
    
    def __str__(self):
        return f'Refunded by {self.user} on {self.date.strftime("%Y-%m-%d %H:%M:%S")}'

core/templates/stock/edit.html
{% extends 'core/base/base.html' %}


{% block title %}Edit Stock{% endblock %}


{% block site_css %}{% endblock %}


{% block body %}
    {% load crispy_forms_tags %}

    <section  class="py-5 px-4">
		<div class="row">
			<div class="col-sm-6 p-3 border mx-auto bg-light">
				<div class="text-center pb-2 border-bottom">
					<h3 class="m-0">Edit Stock</h3>
				</div>

                {% if messages %}
                    {% for message in messages %}
						{% if message.tags == "success" %}
							<div class="alert alert-success p-2 mx-3 mt-3 mb-1"><b>{{ message }}</b></div>
						{% else %}
							<div class="alert alert-danger p-2 mx-3 mt-3 mb-1"><b>{{ message }}</b></div>
						{% endif %}
                    {% endfor %}
                {% endif %}

                <div class="p-2">
                    <form method="POST" action="" class="row g3 pt-1">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <div class="col-md-12 text-center pt-2">
                            <input class="btn btn-success" type="submit" value="Save Stock">
                            <a class="btn btn-primary ms-2" href="{% url 'stocklist' %}"><i class="bi bi-arrow-return-left"></i> Back To List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

{% block site_js %}
<script>
    $(document).ready(function(){
        $("#id_mrp").attr({
            "min" : $("#id_tradePrice").val()  // values (or variables) here
        });
        $("#id_salePrice").attr({
            "min" : $("#id_tradePrice").val()  // values (or variables) here
        });
    });

    $("#id_tradePrice").change(function(){
        $("#id_mrp").attr({
            "min" : $("#id_tradePrice").val()  // values (or variables) here
        });
        $("#id_salePrice").attr({
            "min" : $("#id_tradePrice").val()  // values (or variables) here
        });
    });
</script>
{% endblock %}

core/templates/stock/index.html
{% extends 'core/base/base.html' %}


{% block title %}Stock List{% endblock %}


{% block site_css %}{% endblock %}


{% block body %}

    <section class="py-4 px-5">
		<div class="row">
			<div class="container col-sm-12">
                <div class="pb-2 d-flex justify-content-center align-items-center border-bottom border-secondary border-2">
					<h3 class="m-0 mx-2">Stock List</h3>
				</div>

				<div class="mt-3">
					<a class="btn btn-sm btn-primary" href="{% url 'createpurchase' %}">New Purchase</a>
				</div>

                {% if messages %}
                    {% for message in messages %}
						{% if message.tags == "success" %}
							<div class="alert alert-success p-2 mx-3 mt-3 mb-1"><b>{{ message }}</b></div>
						{% else %}
							<div class="alert alert-danger p-2 mx-3 mt-3 mb-1"><b>{{ message }}</b></div>
						{% endif %}
                    {% endfor %}
                {% endif %}
				
                <div class="mt-3">
                    <table class="table table-sm table-bordered table-hover align-middle text-center" style="font-size: 14px;">
                        <thead class="table-light">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">User</th>
                                <th scope="col">Product</th>
                                <th scope="col">Purchase</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">SalePrice</th>
                                <th scope="col">MRP</th>
                                <th scope="col">Discount</th>
                                <th scope="col">Entry date</th>
                                <th scope="col">Manufacturing date</th>
                                <th scope="col">Expiration date</th>
                                <th scope="col" class="text-center">Action</th>
                              </tr>
                        </thead>
                        <tbody>
                          {% for data in dataset %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{data.user}}</td>
                                <td>{{data.product}}</td>
                                <td>
                                    {% if data.purchase != None %}
                                        <a class="" target="_blank" href="{% url 'editpurchase' data.purchase_id %}">{{data.purchase}}</a>
                                    {% endif %}
                                </td>
                                <td>{{data.quantity}}</td>
                                <td>{{data.salePrice}}</td>
                                <td>{{data.mrp}}</td>
                                <td>{{data.discount}}</td>
                                <td>{{data.entryDate}}</td>
                                <td>{{data.manufacturingDate}}</td>
                                <td>{{data.expirationDate}}</td>
								<td class="text-center">
									<a class="btn btn-sm btn-info" href="{% url 'editstock' data.id %}">Edit</a>
									{% comment %} <form method="POST" class="d-inline" onsubmit="return confirm('Are you sure you want to delete the record?');" action="{% url 'deletepurchase' %}">
										{%csrf_token%}
										<input type="decimal" value="{{data.id}}" name="id" style="display:none;"/>
										<button class="btn btn-sm btn-danger" type="submit" >Delete</button>
									</form> {% endcomment %}
								</td>	
                            </tr>
                          {% endfor %}

                        </tbody>
                    </table>
                </div>

                <div class="">
                    <div class="col-md-12 text-left pt-2">
                        <a class="btn btn-success btn-sm" href="/home/">Back To Home</a>
                    </div>
				</div>
			</div>
		</div>
	</section>


{% endblock %}

{% block site_js %}
<script>

</script>
{% endblock %}